version: '3.1'
services:
  stats-server:
    build: ./stat-service/stat-server
    image: stat-server
    ports:
      - "9090:9090"
    restart: on-failure
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=#dws^54^@3

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=#dws^54^@3

  ewm-service:
    build: ./event-service/event-server
    image: event-server
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SERVER_PORT=8080
      - STAT_SERVER_URL=http://stats-server:9090
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=event
      - POSTGRES_USER=event
      - POSTGRES_PASSWORD=fEW22334fgd

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "8432:5432"
    environment:
      - POSTGRES_DB=event
      - POSTGRES_USER=event
      - POSTGRES_PASSWORD=fEW22334fgd
