version: '3.1'
services:
  stat-server:
    build: ./stat-service/stat-server
    image: stat-server
    ports:
      - "9090:9090"
    restart: on-failure
    depends_on:
      - stat-db
    environment:
      - SERVER_PORT=9090
      - DB_HOST=stat-db
      - DB_PORT=5432
      - DB_NAME=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=#dws^54^@3

  stat-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=#dws^54^@3

#  event-server:
#    build: ./event-service/event-server
#    image: event-server
#    ports:
#      - "9090:8080"
#    restart: on-failure
#    depends_on:
#      - event-db
#      - stat-server
#
#  event-db:
#    image: postgres:14-alpine
#    volumes:
#      - /var/lib/postgresql/data/
#    ports:
#      - "8432:5432"
#    environment:
#      - POSTGRES_DB=event
#      - POSTGRES_USER=event
#      - POSTGRES_PASSWORD="fEW2!2334fgd$"
