drop table if exists hit;
drop table if exists endpoint;

create table endpoint
(
    id  bigint generated by default as identity primary key,
    app varchar(255)  not null,
    uri varchar(1024) not null,

    constraint endpoint_unique_app_and_uri
        unique (app, uri)
);

create table hit
(
    id          bigint generated by default as identity primary key,
    ip          varchar(39)                 not null,
    timestamp   timestamp without time zone not null,
    endpoint_id bigint                      not null
        constraint hit_endpoint_foreign_key
            references endpoint (id) on delete cascade
);